### ISSUE TITLE
Long running then return an empty list (Python version)

### ISSUE THREAD

**Issue by Nanguage** [aidenlab/straw#68]
**Describe the bug**
The `straw` python package can't fetch data correctly, when running:

```
result = matrixObj.getDataFromBinRegion(4000000,6000000,4000000,6000000)
```

It will be blocked for a monment, then return an empty list.

**To Reproduce**
see the Screenshot. My test data can be downloaded from [here](https://github.com/GangCaoLab/CoolBox/blob/master/tests/test_data/dothic_chr9_4000000_6000000.hic).

**Expected behavior**
Return list with readed values.

**Screenshots**
![image](https://user-images.githubusercontent.com/14010939/119794446-1f431400-bf0a-11eb-8fa9-fbe0df5140b3.png)

**Desktop (please complete the following information):**
 - OS: Windows 10, WSL2, Ubuntu 20.10
 - Python version: 3.9.5

**Comment by sa501428** [comment]
The Bin coordinates (in getDataFromBinRegion) are defined as `genomic_position/resolution`, so the issue here will likely be resolved after fixing those coordinates. Alternatively, you may want to use strawC, which is faster, can be installed from the pybind11 folder, and supports the old usage syntax.

**Comment by Nanguage** [comment]
Thanks for your reply. I will try to use strawC.
